name: ifh-gen
channels:
  - conda-forge
dependencies:
  - rdkit=2023.09.4
  - python=3.11.7
  - anaconda::pip
  # Deep Learning dependencies
  - pytorch::pytorch=2.0.1
  - pytorch::cpuonly
  - pyg::pyg=2.4.0
  - lightning=2.1.3
  - torchmetrics=1.2.1
  # utility dependencies
  - cython=3.0.7 # for compiling efficient code on graphs
  - hydra-core=1.3.2 # for handling configuration files in yaml
  - wandb=0.16.2 # for logging training and testing
  # metrics dependencies
  - pygsp=0.5.1 # for graph functions in metrics during evaluation
  - pyemd=1.0.0 # for computing the emd kernel for mmd metrics
  - fcd_torch=1.0.7 # for computing FCD of SMILES
  - dglteam::dgl=1.1.2 # needed for computing GIN metrics for generic graphs
  - pip:
    - git+https://github.com/fabriziocosta/EDeN.git # for computing nspdk
    - python_log_indenter # for better logging
    - hydra-optuna-sweeper