# @package _global_
defaults:
    - ../default_qm9@
    - /experiment/seq_degree/bin_rnd@
    - override /data/dataloader: batch_256

config_name: 'abl1_bin_rnd_qm9_${seed}'
group_name: 'abl1_bin_rnd_qm9'