# @package _global_
defaults:
    - ../default_qm9@
    - /experiment/seq_degree/cat_1_4@
    - override /data/dataloader: batch_256

config_name: 'abl4_catbg_bfs_qm9_${seed}'
group_name: 'abl4_catbg_bfs_qm9'