# @package _global_
defaults:
    - default_comm@
    - /experiment/seq_degree/cat_1_2@

config_name: 'exp2_catsm_bfs_comm_${seed}'
group_name: 'exp2_catsm_bfs_comm'


# chosen hparams
model:
    architecture:
        denoising:
            params:
                transf_config:
                    encdec_hidden_dims:
                        x: 128
                        e: 512
                        y: 512
                    transf_inout_dims:
                        x: 1024
                        e: 64
                        y: 256
                    transf_ffn_dims:
                        x: 128
                        e: 512
                        y: 256
                    transf_hparams:
                        heads: 4
                    num_layers: 9
                gnn_encoder_config:
                    hidden_channels: 64
                    num_layers: 7
        halting:
            params:
                gnn_params:
                    hidden_channels: 1024
                    num_layers: 7
                gnn_out_channels: 256
                readout_hidden_channels: 64
        reinsertion:
            params:
                gnn_params:
                    hidden_channels: 256
                    num_layers: 5
                gnn_out_channels: 64
                readout_hidden_channels: 64