# @package _global_
defaults:
    - default_comm@
    - /experiment/seq_degree/oneshot@

config_name: 'exp4_one_comm_${seed}'
group_name: 'exp4_one_comm'


# chosen hparams
model:
    architecture:
        denoising:
            params:
                transf_config:
                    encdec_hidden_dims:
                        x: 1024
                        e: 64
                        y: 64
                    transf_inout_dims:
                        x: 256
                        e: 256
                        y: 128
                    transf_ffn_dims:
                        x: 128
                        e: 64
                        y: 512
                    transf_hparams:
                        heads: 16
                    num_layers: 9
                gnn_encoder_config:
                    hidden_channels: 1024
                    num_layers: 9