process:
    name: permutation
    params:
        permutation_type: bfs
schedule:
    name: binomial
    params:
        binomial_schedule_type: adaptive_linear
        velocity: 3.0
timesampler:
    name: uniform