# @package _global_
defaults:
    - default_ego_big@
    - /experiment/seq_degree/sequential@

config_name: 'exp1_seq_bfs_ego_big_${seed}'
group_name: 'exp1_seq_bfs_ego_big'

# chosen hparams
model:
    architecture:
        denoising:
            params:
                transf_config:
                    transf_ffn_dims:
                        e: 64
                        x: 256
                        y: 1024
                    transf_inout_dims:
                        e: 128
                        x: 64
                        y: 512
                    encdec_hidden_dims:
                        e: 256
                        x: 128
                        y: 64
                    transf_hparams:
                        heads: 8
                    num_layers: 5
                gnn_encoder_config:
                    hidden_channels: 256
                    num_layers: 9
        halting:
            params:
                gnn_params:
                    num_layers: 9
                    hidden_channels: 128
                gnn_out_channels: 1024
                readout_hidden_channels: 64
        reinsertion:
            params:
                gnn_params:
                    num_layers: 7
                    hidden_channels: 128
                gnn_out_channels: 128
                readout_hidden_channels: 256