# @package _global_
defaults:
    - default_enzymes@
    - /experiment/seq_degree/cat_1_3@

config_name: 'exp2_catsm_bfs_enzymes_${seed}'
group_name: 'exp2_catsm_bfs_enzymes'

# chosen hparams
model:
    architecture:
        denoising:
            params:
                transf_config:
                    encdec_hidden_dims:
                        x: 64
                        e: 1024
                        y: 128
                    transf_inout_dims:
                        x: 256
                        e: 128
                        y: 1024
                    transf_ffn_dims:
                        x: 512
                        e: 256
                        y: 512
                    transf_hparams:
                        heads: 16
                    num_layers: 5
                gnn_encoder_config:
                    hidden_channels: 256
                    num_layers: 11
        halting:
            params:
                gnn_params:
                    hidden_channels: 1024
                    num_layers: 9
                gnn_out_channels: 64
                readout_hidden_channels: 512
        reinsertion:
            params:
                gnn_params:
                    hidden_channels: 64
                    num_layers: 5
                gnn_out_channels: 64
                readout_hidden_channels: 1024