# @package _global_
defaults:
    - default_enzymes@
    - /experiment/seq_degree/cat_1_2_8@

config_name: 'exp3_catbg_bfs_enzymes_${seed}'
group_name: 'exp3_catbg_bfs_enzymes'

# chosen hparams
model:
    architecture:
        denoising:
            params:
                transf_config:
                    encdec_hidden_dims:
                        x: 64
                        e: 128
                        y: 128
                    transf_inout_dims:
                        x: 128
                        e: 256
                        y: 512
                    transf_ffn_dims:
                        x: 1024
                        e: 64
                        y: 512
                    transf_hparams:
                        heads: 8
                    num_layers: 7
                gnn_encoder_config:
                    hidden_channels: 1024
                    num_layers: 9
        halting:
            params:
                gnn_params:
                    hidden_channels: 512
                    num_layers: 7
                gnn_out_channels: 64
                readout_hidden_channels: 256
        reinsertion:
            params:
                gnn_params:
                    hidden_channels: 128
                    num_layers: 7
                gnn_out_channels: 64
                readout_hidden_channels: 512