# @package _global_
defaults:
    - default_qm9@
    - /experiment/seq_degree/cat_1_2@

config_name: 'exp2_catsm_bfs_qm9_${seed}'
group_name: 'exp2_catsm_bfs_qm9'

# chosen hparams
model:
    architecture:
        denoising:
            params:
                transf_config:
                    encdec_hidden_dims:
                        x: 64
                        e: 128
                        y: 128
                    transf_ffn_dims:
                        x: 512
                        e: 128
                        y: 64
                    transf_inout_dims:
                        x: 512
                        e: 64
                        y: 128
                    transf_hparams:
                        heads: 4
                    num_layers: 7
                gnn_encoder_config:
                    hidden_channels: 1024
                    num_layers: 7
        halting:
            params:
                gnn_params:
                    hidden_channels: 64
                    num_layers: 5
                gnn_out_channels: 64
                readout_hidden_channels: 128
        reinsertion:
            params:
                gnn_params:
                    hidden_channels: 1024
                    num_layers: 9
                gnn_out_channels: 1024
                readout_hidden_channels: 256