# @package _global_
defaults:
    - default_qm9@
    - /experiment/seq_degree/oneshot@

config_name: 'exp4_one_qm9_${seed}'
group_name: 'exp4_one_qm9'

# chosen hparams
model:
    architecture:
        denoising:
            params:
                transf_config:
                    encdec_hidden_dims:
                        x: 256
                        e: 256
                        y: 128
                    transf_inout_dims:
                        x: 256
                        e: 512
                        y: 64
                    transf_ffn_dims:
                        x: 64
                        e: 128
                        y: 128
                    transf_hparams:
                        heads: 8
                    num_layers: 5