test:
    generation:
        num_samples: 10000
        batch_size: 2500
    metrics:
        molecular:
            molecular_vun: {}
            molecular_distribution: 
                data_partition: test
        process:
            computational_time: {}
            computational_memory: {}